### ISSUE TITLE
Plugin issues with 3.4

### ISSUE THREAD

**Issue by lacyskidmore** [keremciu/sketch-iconfont#22]
Every time I try to use with 3.4 it's either causing Sketch to shut down or the plugin works once and then won't work again.  I've redownloaded and reinstalled 3 times with no luck :(

**Comment by lacyskidmore** [comment]
We found this in console when using the plugin the second time:
11/11/15 6:27:13.890 PM Ion Icons (Sketch Plugin)[9253]: TypeError: 2.400409678557714e-304 is not a function (evaluating 'doc. currentPage()')
line: 372
sourceURL: /Users/lskidmore/Library/Containers/com.bohemiancoding.sketch3/Data/Library/Application Support/com.bohemiancoding.sketch3/Plugins/iconfont.sketchplugin/Contents/Sketch/add_icon_grid.cocoascript
column: 39

**Comment by SubZane** [comment]
+1 on this one.

**Comment by danielkiedrowski** [comment]
+1 for me too!

**Comment by keremciu** [comment]
Can you try 3.4.1 version of sketch? Because 3.4 could be a problem, they're changing always parameters and functions for plugins. Everytime I'm trying to change this plugin codes for the latest version of sketch.

If it is not work with 3.4.1, I will try again but now it works on my sketch app.

**Comment by danielkiedrowski** [comment]
Where do I get 3.4.1? There is no update in the AppStore. Thanks for your help.

**Comment by keremciu** [comment]
Oh, it's a huge problem. You can find the information about it, https://twitter.com/sketchapp/status/664756659777089537?lang=tr

**Comment by danielkiedrowski** [comment]
Thank you, but that doesn't help. I reinstalled everything fresh from the MAS but nothing changes. Do you have any other idea what I can do to get that running? I still don't have an update for 3.4.1 in my MAS. Thank you again.

**Comment by keremciu** [comment]
Nice to hear, I hope you like it :) I'm developing it for new features, if you have an idea you can share us on https://gitter.im/keremciu/sketch-iconfont
